# Generated by Django 3.0 on 2023-04-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_sales_app', '0002_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAPMC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apmc_name', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('establishment_year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AddMarketPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apmc_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('crop_name', models.CharField(max_length=50)),
                ('qty', models.CharField(max_length=50)),
                ('market_price', models.CharField(max_length=100)),
            ],
        ),
    ]
