# Generated by Django 3.0 on 2023-04-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_sales_app', '0003_addapmc_addmarketprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDiseaseMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('category_name', models.CharField(max_length=50)),
                ('disease_name', models.CharField(max_length=50)),
                ('symptoms', models.CharField(max_length=50)),
                ('pesticides', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AddDiseaseSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30, null=True)),
                ('upload_file', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('category_name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
