# Generated by Django 3.0 on 2023-04-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_sales_app', '0004_adddiseasemaster_adddiseasesolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBuyCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apmc_name', models.CharField(max_length=30, null=True)),
                ('farmer_id', models.CharField(max_length=50, null=True)),
                ('crop_id', models.CharField(max_length=50, null=True)),
                ('quantity', models.CharField(max_length=100, null=True)),
                ('uom', models.CharField(max_length=10, null=True)),
                ('cost', models.CharField(max_length=50, null=True)),
                ('total_cost', models.CharField(max_length=30, null=True)),
                ('buy_date', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('pay_status', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apmc_name', models.CharField(max_length=30, null=True)),
                ('crop_name', models.CharField(max_length=50, null=True)),
                ('quantity', models.CharField(max_length=50, null=True)),
                ('cost', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('uom', models.CharField(max_length=50, null=True)),
                ('stock', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddSellCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apmc_name', models.CharField(max_length=30, null=True)),
                ('farmer_id', models.CharField(max_length=50, null=True)),
                ('crop_name', models.CharField(max_length=50, null=True)),
                ('quantity', models.CharField(max_length=50, null=True)),
                ('uom', models.CharField(max_length=100, null=True)),
                ('selling_date', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
