# Generated by Django 3.0 on 2023-05-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro_sales_app', '0005_addbuycrop_addcrop_addsellcrop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addbuycrop',
            old_name='crop_id',
            new_name='crop_name',
        ),
    ]
